baseURL = "https://itundergrund.netlify.app/"
languageCode = "en-us"
title = "itundergrund"
theme = "hugo-theme-shell"
[Params]
    description = "itu's hacking club"
    favicon = "/static/favicon.ico"
    [Params.Terminal]
        schema = "monokai"
        userName = "it"
        pcName = "undergrund"
        workDir = "admin"
        profile = "flag.txt"

        description = """
        it{undergrund}
        very nice to meet you!
    
        """
        commandDelay = 50
    [Params.Tree]
        use = true
        folderName = "home/itundergrund"
        files = [
            ["who-are-we" , "/post/whoarewe.md"],
            ["next-events", "/post/events.md"],
            ["im-a-beginner-help-me", "/post/skills.md"],
            ["im-ready-to-pwn", "/post/skills.md"]
        ]
