baseURL = "https://sage-rabanadas-77bccc.netlify.app/"
languageCode = "en-us"
title = "itundergrund"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "retro"
    userName = "it"
    pcName = "undergrund"
    workDir = "admin"
    profile = "flag.txt"

    description = """
    it{undergrund}
    very nice to meet you!
  
    """

    [Params.Tree]
    use = true
    folderName = "our-secrets"
    files = [
        ["who are we?" , "https://www.example.com/"],
        ["our achievements", "https://www.example.com/"],
        ["im-a-beginner-help-me", "/works/go.md"],
        ["im-ready-to-pwn", "/works/hugo.md"]
    ]
